# Generated by Django 3.1.3 on 2022-08-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('genre', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=12)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('explanation', models.TextField()),
                ('picture', models.URLField()),
            ],
        ),
    ]
