# Generated by Django 3.1.3 on 2022-08-24 08:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_favoritespot_spot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('EVENT', 'Event'), ('TRIP', 'Trip')], max_length=64)),
                ('place', models.CharField(choices=[('TOKYO', 'Tokyo'), ('KANAGAWA', 'Kanagawa')], max_length=16)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='spot',
            name='request_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='app.requestspot'),
            preserve_default=False,
        ),
    ]
