# Generated by Django 3.1.3 on 2022-08-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220824_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='request_spot',
        ),
    ]
