# Generated by Django 3.1.3 on 2022-08-24 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_spot_request_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestspot',
            name='keyword',
            field=models.CharField(default=django.utils.timezone.now, max_length=16),
            preserve_default=False,
        ),
    ]
