# Generated by Django 3.1.3 on 2022-08-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_requestspot_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='isfavorite',
            field=models.IntegerField(default=0),
        ),
    ]
