# Generated by Django 3.1.3 on 2022-08-25 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_spot_isfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFavoriteSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='favoritespot',
            name='spot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritespots', to='app.spot'),
        ),
        migrations.AlterField(
            model_name='favoritespot',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritespots', to='app.user'),
        ),
    ]
