# Generated by Django 3.1.3 on 2022-08-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220825_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritespot',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
