# Generated by Django 3.1.3 on 2022-08-25 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestfavoritespot',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='favoritespot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.user'),
        ),
    ]
